### ISSUE TITLE
🏗️ 변수 데이터 규격 🏗️ 

### ISSUE THREAD

**Issue by wkjung0624** [Kosta-Juniors/kosta-market#10]
## 회원 (User)
| 변수명 | 타입 | 길이 | 설명 |
| --- | --- | --- | --- |
| username | String | - | 아이디 | 
| password | String | - | 비밀번호 | 
| name | String | - | 이름 | 
| contact | String | - | 연락처 |
| businessNo | String | - | 사업자번호 | 
| deliveryPlace | String | - | 배송지 | 

## 상품 (Product)
| 변수명 | 타입 | 길이 | 설명 |
| --- | --- | --- | --- |
| productNo | int | - | 상품을 식별하는 번호 |
| productName | String | - | 상품의 이름 |
| productPrice | int | - | 상품의 가격 |
| productImgFileName | String | - | 상품 이미지 파일의 이름 |
| productImgPath | String | - | 상품 이미지 파일의 저장 경로 |
| productDescription | String | - | 상품에 대한 상세 설명 |
| productQuantity | int | - | 상품의 재고 수량 |
| categoryNo | int | - | 상품을 분류할 수 있는 카테고리의 번호 |
| categoryName | String | - | 상품 카테고리의 이름 |

## 주문 (Order)
| 변수명 | 타입 | 길이 | 설명 |
| --- | --- | --- | --- |
| orderNo | int | - | 상품주문 시 생성되는 번호, 순차적 증가(seq) |
| orderQuantity | int | - | 상품주문 시 주문수량 |
| orderPrice | int | - | 상품주문 시 결제금액 |
| orderDate | date | - | 상품주문 시 주문시간 |
| paymentMethod | int | - | 결제수단 카드, 무통장 1 카드, 2 무통장, +@ 환불용 |
| orderState | int | - | 주문상태 - 환불 관련 사용 |

**Comment by kimprogramming** [comment]
주문번호 orderNo
구매개수 orderQuantity
주문금액 orderPrice
결제시간 paymentDate
결제수단 paymentMethod(카드, 무통장) 1 카드, 2 무통장, +@ 환불용
주문상태 orderState(환불 관련 사용)

**Comment by wkjung0624** [comment]
번호 >> "No"
~명 >> "Name"

**Comment by wkjung0624** [comment]
| 도메인 | 변수명 | 타입 | 길이 | 설명 |
| --- | --- | --- | --- | --- |
| 회원(User) | userNo | int | - | 회원번호 | 
| 회원,상품,결제 가 들어가는 공간 | 변수명 | String, Int 같은 | 데이터 최대길이 | 이 변수가 뭘 하는지 써주세요|

아래처럼 작성해주세요~

<code> | 회원(User) | userNo | int | - | 회원번호 | </code>

위처럼 작성해주세요~

**Comment by kimprogramming** [comment]
| 주문(Order) | orderNo | INT | - | 상품주문 시 순차적 증가(seq) |
| 주문(Order) | orderQuantity | INT  | - | 상품주문 시 주문수량 |
| 주문(Order) | orderPrice | INT | - | 상품주문 시 결제금액 |
| 주문(Order) | orderDate | DATE | - | 상품주문 시 주문시간 |
| 주문(Order) | paymentMethod | int l -ㅣ결제수단 - 카드, 무통장) 1 카드, 2 무통장, +@ 환불용 | 
| 주문(Order) | orderState | int | - | 주문상태 - 환불 관련 사용 |

**Comment by pro-CAT** [comment]
| 상품(Product) | productNo | int | -  | 상품을 식별하는 번호 |
| 상품(Product) | productName | String | - | 상품의 이름 |
| 상품(Product) | productPrice | int  | - | 상품의 가격 |
| 상품(Product) | productImgFileName | String  | - | 상품 이미지 파일의 이름 |
| 상품(Product) | productImgPath | String | - | 상품 이미지 파일의 저장 경로 |
| 상품(Product) | productDescription | String | - | 상품에 대한 상세 설명 |
| 상품(Product) | productQuantity | int | - | 상품의 재고 수량 |
| 상품(Product) | categoryNo | int | - | 상품을 분류할 수 있는 카테고리의 번호 |
| 상품(Product) | categoryName | String  | - | 상품 카테고리의 이름 |
