### ISSUE TITLE
주문 API 사용방법 수정 요청사항

### ISSUE THREAD

**Issue by wkjung0624** [Kosta-Juniors/kosta-market#104]
### 내용
[#100] 번 이슈에 적힌 API 명세 부분을 아래와 같이 수정해주세요.

- [x] URL 키워드 삭제 : /sheet/list, /sheet
- [x] 명칭 수정 : buyerlist -> buyer, sellerlist -> seller

**Comment by DryHoony** [comment]
[#100] 번 이슈 수정했습니다.
