### ISSUE TITLE
변수명 추가 요청

### ISSUE THREAD

**Issue by kimprogramming** [Kosta-Juniors/kosta-market#15]
상품란 관련 시나리오 작성하면서 건의 사항이 생겼습니다. Product와 Order table란에서 productWriter, orderWriter (foreign key로 session에서 id값을 받아옴) 와 같이 작성자에 대한 테이블 변수를 추가해야 되지 않을까 싶습니다.

**Comment by wkjung0624** [comment]
product_id 를 기준으로 seller 를 찾을 수 있을 것 같네요 :)
DB 테이블 첨부합니다~ [#9]
