### ISSUE TITLE
😕 지금 테이블 구조는 정규화가 필요할까요? 😕 

### ISSUE THREAD

**Issue by wkjung0624** [Kosta-Juniors/kosta-market#31]
[#9] 을 보면 Order 와 Product 테이블 사이에서

Order 는 Product 의 PK 를 받아와 FK 로 추가한 생태입니다. 
> Order.product_id [FK] <---> Product.product_id [PK]

<br>
여기서 Order 를 FK 가 없는 독립적인 테이블로 유지하고 <br><br>
Order_Product 테이블을 생성하여 주문별 상품정보를 매핑하는게 더 나은 방법일까요? <br><br>
의견 부탁드립니다

**Comment by DryHoony** [comment]
Order 테이블에서
FK인 product_id에 종속되는 다른 칼럼(Column)이 없기에, 굳이 추가적인 테이블로 빼지말고
지금 상태를 유지하는 것이 좋아 보입니다.

**Comment by wkjung0624** [comment]
모두 의견 감사합니다 :)
