### ISSUE TITLE
Session에 Authoritization 관련 

### ISSUE THREAD

**Issue by kimprogramming** [Kosta-Juniors/kosta-market#35]
## Session에 seller_id도 추가를 하면 어떨까요?
이러면 판매자가 등록한 상품을 조회할 때나 상품등록과 관련된 Mapper 및 Serivce 코드 작성에
편리해지는 부분이 있어서 그렇습니다.
여러분의 의견은 어떠신가요?

#### 도입 전
- 여러 테이블을 조인해야함
- Service Class 코드 복잡도가 증가함

#### 도입 시
- SQL Mapper 간결화 ( 상품 조회, 상품 등록 등 )
- Service 간결화

#### 현재 Session 의 Key-Value 매핑

> Authentication : <user_id 값>
Authorization : <판매자 구분 bool>

**Comment by wkjung0624** [comment]
> seller_id가 Seller 테이블에서 PK이므로 session에 추가하는 것이 좋아 보입니다. 그렇게 되면 Authorization(boolean)값은 session에서 제외시키는 건가요?
> 
> 즉, Session에 넣어줄 값으로 'Authorization(boolean)' 대신 'seller_id' 로 대체하자는게 맞나요?

네, 판매자 구분이 필요하다면 seller_id 를 세션에 넣어두고 존재여부로 판매자임을 구분하면 될 것으로 보여서입니다.
