### ISSUE TITLE
Order 테이블의 order_price 는 필요없는 Column 일까요?

### ISSUE THREAD

**Issue by wkjung0624** [Kosta-Juniors/kosta-market#37]
### Order 테이블의 order_price 을 제거하고자 합니다.

<pre>
* 주문 테이블 
ㄴ 주문가격 : order_price
ㄴ 주문수량 : order_quantity

* 상품 테이블
ㄴ 상품가격 : product_price
</pre>

**주문가격** 은 **주문수량** x **상품가격** 의 결과값인데 여기서 2가지 의문이 생깁니다.

1. 충분히 계산할 수 있는 값을 Order 테이블에 넣어서 얻을 수 있는 이점이 있는가?

2. 만약 주문가격 컬럼을 제외한다면 어떤 부분에서 문제가 발생할 수 있는가?

여러분들의 생각이 궁금합니다.

**Comment by DryHoony** [comment]
맞습니다.
1. 충분히 계산할 수 있는 값이므로 (결국 종속되는 정보이므로) Order 테이블에 넣음으로 인해 생기는 이점이 없어 보입니다.
2. 반대로 제외한다고 해서 생기는 문제점도 보이지 않습니다. 어짜피 Order테이블과 Product테이블에 각각 query문을 통해 정보를 받아와야 하는데, '주문가격' 칼럼을 제이한다고 해서 달라지진 않을 것 같습니다.

즉, 제외하는게 좋을 것 같습니다.

**Comment by kimprogramming** [comment]
제거하는 것이 좋을 거 같습니다.
1. 충분히 계산 가능한 값이므로 order 테이블에서 제외해도 order테이블과 product 테이블에서 각각 정보를 받아와도 되므로 문제가 될 거 같지 않습니다.
2. 제외한다고 해도 문제가 될 거 같지 않습니다. 사실 나중에 판매자가 판매금액을 정산할 때 이 order price 들만 누적시킬 때 편하지 않을까 했는데 다시 생각해보니 삭제해도 큰 문제는 없을 거 같습니다.

**Comment by wkjung0624** [comment]
order_price 컬럼은 제거하는것으로 결정하겠습니다.
추후 관련사항 업데이트 시 이슈에 업데이트 할께요 😃
