### ISSUE TITLE
DB Table 에 payment 테이블이 추가적으로 필요함

### ISSUE THREAD

**Issue by wkjung0624** [Kosta-Juniors/kosta-market#40]
### Payment 테이블을 새롭게 생성하고자 합니다.

[07월 22일 17:36] 테이블 구성은 아래와 같습니다.
<pre>
주문 테이블 <-- M : 1 --> 상품 테이블

* 주문 테이블 
ㄴ 주문가격 : order_price
ㄴ 주문수량 : order_quantity
ㄴ 결제일자 : order_date
ㄴ 결제수단 : payment_method
ㄴ 주문상태 : order_state

* 상품 테이블
ㄴ 상품가격 : product_price
ㄴ 재고수량 : product_quantity
ㄴ ...
</pre>

[#37]번 이슈에서 문제되었던 order_price 는 제거가 아닌 따로 관리할 필요성을 느꼈습니다.
그 이유는 **과거에 주문했던 내역을 보는 경우 데이터가 변경** 될 수 있기 때문입니다.
아래에 문제가 되는 시나리오를 기재했습니다.

1. 판매자 A 가 시계를 10,000 원에 올림.
2. 사용자 B 가 판매자 A 의 시계를 3월 1일에 1개 구매함.
3. 사용자 B 의 주문내역에는 "[3월 1일] A 시계-10,000" 라고 표기됨
4. 판매자 A 는 이후에 시계값을 20,000 원으로 정정함.
5. 사용자 B 가 5월 1일에 주문내역을 확인함.
6. 과거의 데이터였던 10,000원 이 아닌 20,000원으로 표기됨 (데이터의 불일치 발생)

이러한 이유로 구매 당시 금액인 **order_price 는 어떠한 형태든 유지**되어야 합니다.

그렇기에 '주문' 과 '결제' 를 분리시켜 테이블을 새롭게 생성하고자 합니다.
예시는 아래와 같습니다.

<pre>
결제 테이블 <-- 1 : 1 --> 주문 테이블 <-- M : 1 --> 상품 테이블

* 결제 테이블(Payment)
ㄴ결제가격 : payment_price
ㄴ결제수단 : payment_method
ㄴ결제일자 : payment_date
 
* 주문 테이블 
ㄴ 주문수량 : order_quantity
ㄴ 주문일자 : order_date
ㄴ 주문상태 : order_state

* 상품 테이블
ㄴ 상품가격 : product_price
ㄴ 재고수량 : product_quantity
ㄴ ...
</pre>

주문 테이블에 존재하던 'order_price', 'payment_date', 'payment_method' 를 
공통의 관심사인 **결제**로 묶어 분리시켰습니다.

이를 통해 **데이터의 불일치 문제**를 해결할 수 있습니다.

이번 주말까지 이견이 없다면 위 내용대로 변경하려 합니다.

여러분들의 생각이 궁금합니다.

**Comment by kimprogramming** [comment]
판매자의 가격 변경을 고려하지 못 했었네요. 확실히 구매 당시의 결제금액을 저장할 수단이 필요해보이긴 합니다.
