### ISSUE TITLE
Product 관련 Service 메소드 수정/삭제의 boolean 자료형에 대해 논의하고자 합니다. 

### ISSUE THREAD

**Issue by kimprogramming** [Kosta-Juniors/kosta-market#41]
상품 수정/삭제와 관련하여 코딩을 하면서 **boolean 타입의 효율성**에 대해 고민이 생겼습니다.
설계 초기에는 상품Table의 수정이나 삭제 메소드 자료형을
잘 동작되는지 판별하기 위해 boolean 타입으로 지정했습니다.
하지만 DB 테이블을 설계하는 과정에서
Seller_Product 테이블, Product_Category 테이블이 생겨나면서 문제가 발생했습니다.

boolean 타입으로 할 경우 다음과 같은 문제가 발생합니다.
1, 삭제 판별 유무를 위해 3개의 DTO 클래스를 생산해야 한다.
2. Service 단에서도 이를 점검하기 위해 코드적으로 복잡해진다.

이러한 점들을 고려했을 때 boolean 형을 고집할 필요가 있나 싶습니다.
여러분들의 의견은 어떤가요?

**Comment by wkjung0624** [comment]
1. product_id 를 참조키(FK) 로 쓰는 모든 테이블은 **ON DELETE CASCADE** 로 설정되어있습니다. 따라서 product 만 확인하면 될 것으로 보입니다.
2. -
