### ISSUE TITLE
MYSQL) AUTO_INCREMENT 되는 데이터 가져오는 방법

### ISSUE THREAD

**Issue by kimprogramming** [Kosta-Juniors/kosta-market#46]
**위 내용은 다음과 같은 경우에 필요합니다.**
- 상품 등록 할 때와 같이  **여러 테이블에 데이터를 동시 삽입**해야 되는 경우
EX) PRODUCT 테이블에 데이터 추가 시
      USER_PRODUCT 테이블이나
      PRODUCT_CATEGORY 테이블에도
      상품 등록 시 AUTOINCREMENT 된 product_id값이 필요합니다.
      따라서 이를 위한 product_id값을 가져오는 Mapper를 추가해야 합니다.
      또한 이를 Serivice 단 코드 작성 시에도 고려해야 합니다.

**첫번째 방법** 
SELECT AUTO_INCREMENT

FROM information_schema.tables

WHERE table_name = 'table name'

AND table_schema = '스키마 이름' ;

현재 우리가 사용하는 스키마 이름은 kosta_market

**두번째 방법**
select LAST_INSERT_ID() 
가장 최근에 INSERT시에 입력된 INCREMENT ID값을 가져올 수 있다.
중간에 다른 사용자에 의해 글이 추가되더라도 내가 작성할때 부여된 INCREMENT값이 가지고 옴.
같은 커넥션 안에서만 정상적인 결과가 나온다.

단, LAST_INSERT_ID() 는 table을 사용할수 없다고 한다. 

출처
https://yg-dad.tistory.com/1099

**Comment by wkjung0624** [comment]
확인했습니다. 감사합니다 :)
