### ISSUE TITLE
상품삭제 기능과 관련하여 DB 쪽 수정이 필요

### ISSUE THREAD

**Issue by kimprogramming** [Kosta-Juniors/kosta-market#66]
현재 삭제 기능 수행을 위해 테스팅하는 동안 다음과 같은 에러가 발생하였습니다.

; Cannot delete or update a parent row: a foreign key constraint fails (`kosta_market`.`TBL_ORDER`, CONSTRAINT `TBL_ORDER_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `TBL_PRODUCT` (`product_id`)); nested exception is java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`kosta_market`.`TBL_ORDER`, CONSTRAINT `TBL_ORDER_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `TBL_PRODUCT` (`product_id`))] with root cause

DB 쪽을 살펴보니 현재 TBL_ORDER 의 외래키인 product_id의 delete 기능과 관련하여
restrict으로 설정되어 있어서 상품 삭제가 불가능합니다.
따라서 외래키 해제 혹은 설정 변경이 필요할 거 같습니다.

**Comment by wkjung0624** [comment]
#### 요약
- 각 테이블 별 <code>deleted</code> 컬럼을 추가하여 **Soft Delete** 방식을 적용한다.

#### 내용

위에서 언급된 **외래키 제거**를 하게된다면 <code>주문</code>과 <code>상품</code> 테이블 간 데이터의 무결성 유지할 수 없고,
외래키 삭제로 얻을 수 있는 이점이 현행을 유지하는 것보다 나을지 의문입니다.

제 생각은 <code>주문</code> 데이터는 <code>상품</code> 데이터가 삭제 되었어도 유지될 수 있도록
<code>상품</code> 테이블에 <code>deleted</code> 컬럼을 추가하고 **상품이 삭제 되었을 때 'Y', 그렇지 않으면 'N'** 으로
상태를 관리하는 **Soft Delete** 방식을 적용하여 해결하는게 좋아보입니다.

혹여나 다른 의견있으시다면 코멘트 남겨주세요! 😀

#### 관련 자료
- [Codeproject, How to delete products and persist order history when OrderDetails is coupled to Product.](https://www.codeproject.com/Questions/542424/OrderDetailspluscoupledplustoplusProductplustables)
- [Stackoverflow, storing-products-in-order-product-is-deleted-after-order-placed](https://stackoverflow.com/questions/42954063/storing-products-in-order-product-is-deleted-after-order-placed)
- [Velog, hard-delete-soft-delete](https://velog.io/@taeha7b/hard-delete-softdelete)
- [Okky, 왜 대용량 디비에서는 외래키를 안쓰나요?](https://okky.kr/article/586565)

**Comment by wkjung0624** [comment]
이 문제점과 관련해 [#42]번 이슈도 유사한 경우이므로 Close 하겠습니다.
