### ISSUE TITLE
✨ 상품 도메인 To do List (08.08~08.12)

### ISSUE THREAD

**Issue by wkjung0624** [Kosta-Juniors/kosta-market#68]
##### To do
-  [x] 상품 이미지 관련 기능 추가
   - [x] 이미지 파일 @MultipartFile 을 이용하여 저장
   - [x] 이미지 메타정보(파일명, 파일경로)는 DB 에 저장
   - [x] 프론트에서 이미지 파일 불러오기
- [x] 기능 업데이트 될 때마다 Commit
- [x] 카테고리 리스트 조회 API 추가

**Comment by kimprogramming** [comment]
확인했습니다.
