### ISSUE TITLE
상품 카테고리 리스트 관련 고려할 사항

### ISSUE THREAD

**Issue by kimprogramming** [Kosta-Juniors/kosta-market#71]
기존에는 카테고리 목록을 ArrayList로 받아 Model 방식으로 뷰 단에 데이터를 전달했습니다.
하지만 현재는 
**Category 관련 url을 별도로 구현
ResponseEntity로 데이터를 반환
JSON 형태 전달 장려**
로 하고 있습니다.

이에 따라 List 타입으로 Mapper에서 받아온 카테고리 목록을
**ArrayList->JSONArray -> JSONObject** 으로 변환하여
ResponseEntity를 통해 값을 전달해야 하나 고민하고 있습니다. 

정리
1. 맵퍼에서 받아온 카테고리 목록을 JSONObject로 반환해줘야 하는가?
(arrayList->JSONObject로 변환해야 하나)

**Comment by wkjung0624** [comment]
> Category 관련 url을 별도로 구현
이 부분 코드는 어디있는건가요? 별도로 구현했다는게 어떤건지 모르겠어요ㅠㅠ
