### ISSUE TITLE
🧑‍🎓 장바구니 기능은 DB로 구현하는게 최선일까요? 🧑‍🎓

### ISSUE THREAD

**Issue by wkjung0624** [Kosta-Juniors/kosta-market#76]
### 요약
- 장바구니 기능은 Cookie 를 이용해서 구현하는건 어떤가?

### 내용
<code>상품</code> 도메인의 <code>장바구니</code> 기능을 구현하기 위해 자료를 찾아보니 여러 자료들이 
장바구니 데이터는 디스크 방식의 DB 에 저장하여 불러오는 형태였습니다.

그런데 생각해보니 장바구니 데이터를 DB 에 저장하는게 과연 효율적일지 의구심이 들었습니다.

그 이유로 사용자의 변심에 따라 장바구니 데이터의 잦은 변동이 있을 수 있는데 
DB 에 데이터를 저장하고 불러올 때 마다 **네트워크 대역폭을 소비**하고 **Disk I/O 를 발생**시키며
구매하지 않고 놔두는 경우 **정크 데이터**가 쌓이는 문제점이 있어 비용이 높은 작업이라 생각되었기 때문입니다.

그러므로 서버에서 처리하는게 아닌 클라이언트에서 처리 가능하도록 Cookie 를 이용하면 어떨까 싶습니다
제가 생각한 Cookie 를 이용한 장바구니 데이터 관리의 장단점은 아래와 같습니다.

#### 장점
- DB 에 Disk I/O 가 일어나지 않음
- 네트워크 대역폭을 확보할 수 있음

#### 단점
- 브라우저의 '사용자 기록 삭제' 에 장바구니 데이터가 지워질 수 있음
- 상품이 변경될 때 추적이 어려움
- 서버로 데이터를 보내지 않으므로, 소비 성향 데이터 분석이 어려움

아직까지는 서버에 영향이 적은 Cookie 를 이용하는 방식이 더 효율적으로 보이
여러분들의 생각은 어떠신가요? 의견 부탁드립니다 🙇‍♂️

### 참고
- [Wiki, HTTP Cookie 란?](https://ko.wikipedia.org/wiki/HTTP_%EC%BF%A0%ED%82%A4)

**Comment by kimprogramming** [comment]
사실 어느 방법이나 장바구니 구현은 가능 합니다.
만약 쿠키를 이용 한다면 DB를 이용 하는 방법보다 동시 접속자가 많은 경우
서버의 부하나 속도 면에서 이득을 볼수 있습니다.
하지만 사용자가 쿠키 사용을 거부 한 경우라던지 개인보호 강화 정책으로 인한 쿠키나 세션 값 이용이 자유롭지 못한 문제 등을 고려해야 합니다.

**Comment by wkjung0624** [comment]
개인정보 처리방침에 보면 "자동수집 장치 설치 운영 및 거부"에 관한 내용이 있어 Cookie 만으로 장바구니 기능을 구현하기엔 어려움이 있을 것 같네요. 답변 감사합니다!
