### ISSUE TITLE
추천상품,상품개수,상품관련댓글개수 기능과 관련한 API 수정을 요청합니다.

### ISSUE THREAD

**Issue by kimprogramming** [Kosta-Juniors/kosta-market#89]
현재 임시로 댓글 관련 API를 작성하였는데 
이와 관련하여 수정이 필요한 거 같습니다.

- 상품 개수 가져오기 @GetMapping(value = "/api/product/count")
- 상품 리뷰 개수 가져오기 @GetMapping(value = "/api/product/{product_id}/comment/count")
- 카테고리 관련 상품 5가지 추천 @GetMapping(value = "/api/product/{product_id}/category/{category_id}")
- Top rated 상품 3가지 가져오기 @GetMapping(value = "/api/product/top")

**Comment by wkjung0624** [comment]
### 요약
- 3, 4번 API 는 조건에 따라 분리되는 데이터이므로 RequestParam 형태로 처리해야합니다
- 카테고리 관련 상품 5가지 추천 : <code>/api/product?{category:n}{size:5}</code>
- Top rated 상품 3가지 가져오기 : <code>/api/product?{sortby:'score'}{size:3}</code>

### 내용
"카테고리 관련상품 5가지 추천", "Top rated 상품 3가지 가져오기" 는 
가져오는 값의 형태가 <code>/api/product</code> 와 동일합니다.

지금까지 **RequestParam** 으로 처리한 것들은 **특정 데이터를 찾기 위한 필터의 역할**을 했고
**Path Variables** 는 **중복되지 않는 고유한 데이터를 지정**하는데 사용됐습니다.

그런데 위에서 제안하신 URL 은 아래와 같은 문제가 있습니다.

#### 상단 2개 API URL 의 문제점
1. **카테고리 관련 상품 5가지 추천 API**
- 카테고리 관련 5개 상품을 가져올때는 특정 상품을 지정하는 <code>product_id</code>는  사용할 필요가 없어보입니다.
- 카테고리는 **중복이 가능한 값**이고, 카테고리를 Path Variables 로 처리하여 고유한 값을 가져올 때<br>그 값은 <code>카테고리 번호</code>, <code> 카테고리 이름</code>이 되어야합니다.
- URL 만 보고 해석한다면 **"특정 상품에서 특정 카테고리를 가져온다"** 라고 해석될 수 있습니다. <br>해석한 기준은 아래에 있습니다<br>
> 제안하신 URL 주소
: /api/product/{product_id}/category/{category_id} <br>
특정 상품 : /product/{product_id}
 ~ 에서 : '/' 기준 우측 도메인이 좌측 도메인에 연계된 데이터
특정 카테고리 : /category/{category_id}
가져온다 : @GetMapping

2. **Top rated 상품 3가지 가져오기 API**
- 상위 n개 상품을 **가변적으로 받아올 수 없고**, 3개로 고정되어 있다는 점
- <code>/api/product/</code> 뒤에 <code>top</code> 이란 동사를 붙혀 "상위 3개 상품"을 가져오는 특별한 지시자를 생성하였지만, <br> 등록된 상품들에서 조회할 때 필요한 **검색 조건**이라는 점에서 **RequestParam** 을 이용하여도 큰 문제가 없다는 점 <br>

위와 같은 이유로 언급된 **"카테고리 관련상품 5가지 추천"**, **"Top rated 상품 3가지 가져오기"** 는
새로운 URL 을 가지기보다 <code>/api/product</code> 에 RequestParam 만 추가하여 기존의 규약을 지키는 것이 좋을 듯합니다.

저는 위 2개 API 를 아래와 같은 API 주소로 바꾸길 제안합니다.

- 카테고리 관련 상품 5가지 추천 : <code>/api/product?{category:n}{size:5}</code>
- Top rated 상품 3가지 가져오기 : <code>/api/product?{sortby:'score'}{size:3}</code>

먼저 **"카테고리 관련 상품 5가지 추천"** 부터 보면 문제로 제기했던 <code>product_id</code> 는 더 이상 사용하지 않습니다.
또한 중복값이 가능한 <code>category_id</code> 는 조건에 해당되는 **Request Param** 으로 넘겨서 필요 시만 사용할 수 있도록
변경하였습니다.

이어서 **"Top rated 상품 3가지 가져오기"** 도 마찬가지로 URL 끝에 <code>top</code> 을 제거하고, RequestParam 인 <code>sortBy</code> 와 <code>size</code> 로 대체하였습니다. <code>sortBy</code> 는 상품정렬 기준을 지정할 때, <code>size</code> 는 불러올 갯수를 지정할 때 사용됩니다. 두 개의 RequestParam 을 나눔으로 **가변적인 데이터 요청** 을 처리할 수 있고, 특별한 지시자 없이도 기존의 API 에 포함시킴으로 자칫 **중복될 수 있는 기능**을 제거하였습니다.
 
※ "/api/product/top" 의 경우는 기존의 규칙을 벗어나지 않았고, 큰 문제는 없었지만 **비슷한 기능의 중복 가능성** 을 염두에 뒀던지라
RequestParam 에 빼는것으로 결정했습니다. 혹여나 더 나은 방법이 있을 수 있으니 한번 고민해보셔도 좋을 것 같습니다 😄

**Comment by wkjung0624** [comment]
[#92] 에 답변 남겨두었습니다! 참고하세요 :)
